version: "3"
services:
  varnish:
    image: jonbaldie/varnish
    ports:
      - 8000:80
    links:
      - searchrunner1
      - searchrunner2
      - searchrunner3
    depends_on:
      - searchrunner1
      - searchrunner2
      - searchrunner3
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
  searchrunner1:
    build:
      context: .
    environment:
      WEB_APP: host.docker.internal
      VIRTUAL_HOST: localhost
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
  searchrunner2:
    build:
      context: .
    environment:
      WEB_APP: host.docker.internal
      VIRTUAL_HOST: localhost
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
  searchrunner3:
    build:
      context: .
    environment:
      WEB_APP: host.docker.internal
      VIRTUAL_HOST: localhost
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
