version: "3"
services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - 8000:80
    depends_on:
      - searchrunner
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  searchrunner:
    build:
      context: .
    environment:
      WEB_APP: host.docker.internal
      VIRTUAL_HOST: localhost
      REDIS_HOST: redis
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - redis
    command: ["npm", "start"]
  redis:
    image: redis
